/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomMF: typeof import('./src/components/BottomMF.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    Figure: typeof import('./src/components/Figure.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LeftPanel: typeof import('./src/components/LeftPanel.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    Reocords: typeof import('./src/components/Reocords.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
    RobotAssistant: typeof import('./src/components/RobotAssistant/RobotAssistant.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCard: typeof import('./src/components/SelectCard.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TopTable: typeof import('./src/components/TopTable.vue')['default']
  }
}
